// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_content_delivery_bucket": "climbingapp-20191103143415-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://climbingapp-20191103143415-hostingbucket-dev.s3-website-us-east-1.amazonaws.com",
    "aws_cognito_identity_pool_id": "us-east-1:a4a5e02d-915d-4d7c-b9f4-3cb785b689d0",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_PibDQ5vl1",
    "aws_user_pools_web_client_id": "4bm05qkpb6jojitt7861nsst30",
    "oauth": {},
    "aws_mobile_analytics_app_id": "4d73d5e9611e4a3bb978975b30de32b3",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_user_files_s3_bucket": "betavideos-dev",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://eyz3rxhcifggthicerq6degdfy.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
